name: Build
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  nix-build:
    name: nix-build
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v16
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and test
        run: nix-build -A tailscale-lb
