name: Build
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '!infra/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  nix-build:
    name: nix build
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Set up cache
        uses: zombiezen/setup-nix-cache-action@v0.1.0
        with:
          substituters: s3://zombiezen-tailscale-lb-nixcache?endpoint=https://storage.googleapis.com
          secret_keys: ${{ secrets.NIX_PRIVATE_KEY }}
          aws_access_key_id: ${{ secrets.GCS_HMAC_ACCESS_ID }}
          aws_secret_access_key: ${{ secrets.GCS_HMAC_SECRET_ACCESS_KEY }}
      - name: Check out code
        uses: actions/checkout@v2
      - id: build
        name: Build and test
        run: |
          nix build '.#ci'
          echo "result=$(readlink -f result)" >> "$GITHUB_OUTPUT"
      - name: Upload Docker images
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: ${{ steps.build.outputs.result }}/docker-image-*.tar.gz

permissions:
  contents: read
